name: BERBAGIT
title: BERBAGIT | Berbagi Tentang IT
description: Web yang berisi info IT dan tutorial belajar pemrograman seperti HTML, CSS, Bootstrap, JavaScript, Jquery, PHP, SQL, Laravel dan pemrograman lainnya.
tags:
  - html
  - css
  - javascript
  - php
  - laravel
email: berbagit45@gmail.com
disqus_username: berbagit
show_hero: true
menu:
  - title: Home
    url: /
  - title: HTML
    url: /html
  - title: CSS
    url: /css
  - title: JavaScript
    url: /javascript
  - title: Tutorial Lainnya
    url: /tutorial
  - title: Forum
    url: /forum
  - title: Blog
    url: /category/blog
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feedburner
  - title: Cari Apa
    url: /cari